---
title: "Data Science for Public Policy"
subtitle: "Assignment 04: Data Visualization, Quarto, and Git"
author: "Ronin McCobb and Daniela Nagar"
format: 
  pdf:
    code-line-numbers: true
execute: 
  warning: false
urlcolor: blue
editor_options: 
  chunk_output_type: console
  
---

\vspace{0.1in}

Data Source: [IPUMS](https://www.ipums.org/)

```{r}
library(tidyverse)
library(ipumsr)
library(srvyr)
library(haven)
```

```{r}
ddi <- read_ipums_ddi("data/cps_00004.xml")
data <- read_ipums_micro(ddi)

```

```{r}
#Graph 1

data |>
  filter(FSRAWSCRA < 11 & FSRAWSCRA > 0 ) |>
  ggplot(aes(x=FSRAWSCRA)) +
  geom_bar(width = 1, fill = "blue") +
   labs(
      title = "Food Security Scores in the United States",
      caption = "Sarah Flood, Miriam King, Renae Rodgers, Steven Ruggles,
J. Robert Warren, Daniel Backman, Annie Chen, Grace Cooper, Stephanie Richards,
Megan Schouweiler, and Michael Westberry. IPUMS CPS Version 12.0 [dataset]. 
Minneapolis, MN: IPUMS, 2024. https://doi.org/10.18128/D030.V12.0"
    ) +
  xlab("Score") +
  ylab("Count")

```

```{r}
#Data Visualization 2: Average Family Income by State Among Wealthiest States
avg_faminc <- data |>
  group_by(STATEFIP) |>
  summarize(avg_faminc = mean(FAMINC, na.rm = TRUE)) |>
  filter(avg_faminc >=785) |>
mutate(
    STATEFIP = as.numeric(STATEFIP))

ggplot(avg_faminc, aes(x = STATEFIP, y = avg_faminc)) +
  geom_point(color = "blue", size = 3, shape = 18) +
  geom_text(aes(label = STATEFIP), vjust = -0.5, size = 3) + 
  labs (
    title = "Average Family Income by State Among Wealthiest States",
    x = "State Code",
    y = "Average Family Income"
  )
  
#Written interpretation: This graph identifies the 7 wealthiest states based on average family income. Each point has the number state on top of it, so we can identify which 7 states are the wealthiest. We will use the FIPS codes of those states to inform our next visualization.

```


```{r}
#Data Visualization 3: Number of Respondents in the 7 Wealthiest States with Highest Food Insecurity Score
rich_state_codes <- c(9, 24, 27, 33, 34, 44, 49)
avg_fsrawscra <- data |>
  group_by(STATEFIP) |>
  summarize(num_10 = sum(FSRAWSCRA == 10, na.rm = TRUE)) |>
  summarize(avg_num_10 = mean(num_10)) |> 
  pull(avg_num_10)

data |>
filter(FSRAWSCRA == 10, STATEFIP %in% rich_state_codes) |>
  mutate(STATEFIP = as.numeric(STATEFIP)) |> 
  ggplot(aes(x = factor(STATEFIP), y = FSRAWSCRA, alpha = 0.2)) +
geom_col(fill="pink") +
  geom_hline(yintercept = avg_fsrawscra, linetype = "dotted", color = "magenta", size = 1) +
  labs(
    title = "Number of Respondents in the 7 Wealthiest States with a Food Insecurity Score of 10",
    x = "State Code",
    y = "Food Insecurity Score"
  )


#Written interpretation: This chart shows how many respondents with food insecurity score of 10 each of the 7 wealthiest states has. The dotted line shows, by comparison, the average number of respondents with a food insecurity score of 10 across all other states in the US.

```
